apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-4
  namespace: argocd
  annotations:
    # MALFORMED - unquoted value starting with comma breaks YAML
    owner: ", admin@example.com"
spec:
  project: guestbook-4
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-4
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
