apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-3
  namespace: argocd
spec:
  project: guestbook-3
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
